### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by ChunGui-MengLiRen** [Lushenggang/js-tree-tool#2]
大佬，最近做项目需要操作tree结构数据，看到了tree-tool。请教一下，如何在当前节点下添加子节点，以及如何把当前节点移动到指定节点中？

![tree](https://user-images.githubusercontent.com/76636186/124923691-49214780-e02d-11eb-80d0-1adde8edb87b.png)

**Comment by wintc23** [comment]
能拿到node，那增删都不难啦？
添加：
node.children.push(child);
移动就是当前node.children列表删除子节点，然后添加到targetNode。
